### ISSUE TITLE
No examples, not clear how to use it

### ISSUE THREAD

**Issue by K0stIa** [rozumden/meanshift#1]

**Comment by rozumden** [comment]
Hi @K0stIa, thanks for your comment. An example how to use meanshift is provided in the [Matlab wrapper](https://github.com/rozumden/meanshift/blob/master/matlab/%2BMMS/Meanshift.m). For testing it on artificial data please check the [test file](https://github.com/rozumden/meanshift/blob/master/matlab/%2BMMS/demo.m). If it's still unclear, please let us know.

**Comment by K0stIa** [comment]
Hi Denis,

Then I'd suggest to call it demo.m instead. It worth to mention in README that demo is provided.

Regards.

**Comment by rozumden** [comment]
Hi @K0stIa, the file has been renamed and it's mentioned in the README now.
